Global:
  use_visualdl: False
  use_wandb: True
  epoch_num: 100 
  use_amp: True
  amp_level: O2
  amp_dtype: float16
  use_gpu: True
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_korean_numberplate_exp2/   # ✅ 변경됨
  save_epoch_step: 1
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/rec_mv3_none_bilstm_ctc/inference   # ✅ 이전 모델 불러오기
  # checkpoints 항목 제거 (기존 optimizer state 불러오지 않기)
  save_inference_dir:
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ./ppocr/utils/numberplate_dict.txt
  max_text_length: 16
  infer_mode: False
  use_space_char: False

wandb:
  project: korean_numberplate_ocr
  name: exp2  # ✅ WandB run 이름 변경
  entity: 1924013-
  save_dir: ./output/rec_korean_numberplate_exp2/

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Step
    learning_rate: 0.001
    step_size: 20       # ← 몇 에폭마다 줄일지 설정
    gamma: 0.1
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode
  character_dict_path: ./ppocr/utils/numberplate_dict.txt
  use_space_char: False

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./TrainingImg
    label_file_list:
      - ./TrainLabel/rec_gt.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - RecAug:
          use_tia: true     # ✅ TIA 적용
          aug_prob: 0.5     # ✅ 50% 확률로 적용
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 160]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: True
    num_workers: 10
    use_shared_memory: False

Eval:
  interval: 100
  dataset:
    name: SimpleDataSet
    data_dir: ./evalImg
    label_file_list:
      - ./evalLabel/eval_gt.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 160]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    batch_size_per_card: 128
    drop_last: False
    num_workers: 10
  use_shared_memory: False