Global:
  infer_mode: true
  use_gpu: true
  save_inference_dir: ./inference_model/
  character_dict_path: ./numberplate_dict.txt
  max_text_length: 16
  use_space_char: false
  pretrained_model: ./best_accuracy
  infer_img: ./inference/sample.jpg

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    name: ResNet
    layers: 18
    disable_se: true
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.0001
    out_channels: 121

PostProcess:
  name: CTCLabelDecode
  character_dict_path: ./numberplate_dict.txt
  use_space_char: false

Eval:
  dataset:
    transforms:
      - DecodeImage:
          img_mode: BGR
      - Resize:
          width: 320
          height: 32
      - NormalizeImage:
          mean: [127.5, 127.5, 127.5]
          std: [127.5, 127.5, 127.5]
          scale: 1.0
      - ToCHWImage: {}
      - KeepKeys:
          keep_keys: ['image']

  loader:
    shuffle: false
    batch_size_per_card: 128
    drop_last: false
    num_workers: 10
  use_shared_memory: false

